Doc12
Arquisoft/wiq_en3b pull request #35
Opened 2024-02-27 20:29 UTC by IyanRobles

Added terms to section 12 of the documentation (glossary)

2024-02-28 08:08 UTC, Raulms29 requested changes
If I remember correctly, we shouldn't include terms such as React or Express or TypeScript, and include terms that are on the domain of our application such as question.

2024-02-28 18:36 UTC, IyanRobles commented
> If I remember correctly, we shouldn't include terms such as React or Express or TypeScript, and include terms that are on the domain of our application such as question.

Well, I was using [this documentation](https://biking.michael-simons.eu/docs/index.html#section-glossary) from the [arc42 examples](https://arc42.org/examples) as a reference, but it is true that the rest of example documentations do not include this kind of terms and just focus on domain ones, so I will change that.

2024-02-28 18:39 UTC, Raulms29 commented
Don't remove it for now. We can comment it tomorrow on the meeting with the rest of the team.

2024-03-10 17:36 UTC, Raulms29 approved these changes

2024-03-10 17:37 UTC, merged