Questionservice Tests and Refactoring
Arquisoft/wiq_en3b pull request #78
Opened 2024-03-20 23:28 UTC by didierrc

QuestionService improvments to include:
- Tests of Endpoints, QuestionController and QuestionGenerator Service. Usage of Mocks to avoid Flaky Tests due to API or DB calls. Made by @didierrc
- Documentation of QuestionGenerator Service and Refactoring to have a much clean code. Made by @Raulms29 
- Project set-up for running tests @Raulms29

2024-03-20 23:35 UTC, Raulms29 requested changes
It seems that I forgot to include the execution of the tests on the build.yml. This means that the tests for the questionservice are not being automatically executed when creating a PR.
I will change it for tomorrow.

2024-03-21 07:16 UTC, Raulms29 approved these changes

2024-03-21 08:46 UTC, didierrc commented
I have removed unused packages from QuestionService. We cannot have more dependencies than necessary

2024-03-21 12:04 UTC, IyanRobles approved these changes

2024-03-21 12:21 UTC, merged